#!/usr/bin/env python3
"""Generate PyReveal demo assets embedded in the documentation site."""

from pathlib import Path

from pyreveal import ColorBackground, PyReveal, Slide

ROOT = Path(__file__).resolve().parents[1]
DEMO_DIR = ROOT / "docs" / "assets" / "demo"
INDEX_PATH = ROOT / "docs" / "index.md"
SHOWCASE_START = '<div class="pyreveal-inline-deck">'
SHOWCASE_END = "</div>\n</div>"


def build_interactive_deck() -> None:
    presentation = PyReveal(title="PyReveal", theme="dracula", transition="fade")
    presentation.configure(
        embedded=True,
        controls=True,
        progress=True,
        hash=False,
        slideNumber="c",
        width=960,
        height=540,
    )

    presentation.add_slide(
        Slide(
            content="""
            <h2 style="font-size:2.4em;font-weight:700;">PyReveal</h2>
            <p style="opacity:0.85;font-size:1.1em;">Presentations from Python</p>
            """,
            background=ColorBackground("#1e1e2e"),
        )
    )

    features = Slide(content="<h3>Built with code</h3>")
    features.add_vertical_slide(
        Slide(content="<p>Slide, Element, and Style objects</p>")
    )
    features.add_vertical_slide(
        Slide(content="<p>Reveal.js 6 themes and transitions</p>")
    )
    features.add_vertical_slide(
        Slide(content="<p>Self-contained HTML export</p>")
    )
    presentation.add_slide(features)

    presentation.add_slide(
        Slide(
            content="""
            <h3>Try it</h3>
            <pre><code data-trim data-noescape>
from pyreveal import PyReveal, Slide

deck = PyReveal(theme="dracula")
deck.add_slide(Slide(content="&lt;h1&gt;Hello&lt;/h1&gt;"))
deck.save_to_file("talk.html")
            </code></pre>
            """,
        )
    )

    DEMO_DIR.mkdir(parents=True, exist_ok=True)
    presentation.save_to_file("preview.html", output_dir=str(DEMO_DIR))


def sync_inline_showcase_to_index() -> None:
    """Inject freshly rendered slide HTML into docs/index.md."""
    presentation = PyReveal(title="Showcase", theme="black", transition="none")
    slide = Slide(
        content="""
        <div class="showcase-inner">
          <span class="showcase-badge">Generated by PyReveal</span>
          <h2>Slides as code</h2>
          <p>Compose decks with Python, export reveal.js HTML.</p>
        </div>
        """,
        background=ColorBackground("#11111b"),
    )
    rendered = slide.render()
    index = INDEX_PATH.read_text(encoding="utf-8")
    start = index.find(SHOWCASE_START)
    end = index.find(SHOWCASE_END, start)
    if start == -1 or end == -1:
        raise RuntimeError("Could not find showcase markers in docs/index.md")
    replacement = f'{SHOWCASE_START}{rendered}'
    INDEX_PATH.write_text(
        index[:start] + replacement + index[end:],
        encoding="utf-8",
    )


def main() -> None:
    build_interactive_deck()
    sync_inline_showcase_to_index()
    print(f"Demo written to {DEMO_DIR}")
    print(f"Inline showcase synced into {INDEX_PATH}")


if __name__ == "__main__":
    main()